version: 0.0
os: linux

files:
  - source: scripts/
    destination: /home/ubuntu
  - source: image_tag.txt
    destination: /home/ubuntu

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ubuntu

  BeforeInstall:
    - location: before.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: validate.sh
      timeout: 300
      runas: ubuntu
