version: 0.0
os: linux

files:
  - source: scripts/
    destination: /home/ubuntu/deploy
  - source: image_tag.txt
    destination: /home/ubuntu/deploy

hooks:
  ApplicationStop:
    - location: deploy/stop.sh
      timeout: 300
      runas: ubuntu

  BeforeInstall:
    - location: deploy/before.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: deploy/start.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: deploy/validate.sh
      timeout: 300
      runas: ubuntu
