version: 0.0
os: linux

files:
  - source: scripts/
    destination: /home/ubuntu/deploy-scripts

hooks:
  BeforeInstall:
    - location: deploy-scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: deploy-scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: deploy-scripts/stop_server.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: deploy-scripts/start_server.sh
      timeout: 300
      runas: ubuntu
