version: '3.8'

services:

  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - backend_logs:/app/logs

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  backend_logs:  # 백엔드 로그 저장
  frontend_build:  # 프론트엔드 빌드 캐싱
