spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://rds.g1enn.site:3306/weekly_db
    username: admin
    password: alstjr11
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
