name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # frontend 폴더 안의 파일이 변경될 때만 실행

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # 1. GitHub Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정 (React 빌드)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. 의존성 설치
      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      # 4. React 빌드 (S3에 업로드할 정적  파일)
      - name: Build Project
        run: |
          cd frontend
          npm run build

      # 5. AWS S3 로그인 후 빌드된 파일 업로드
      - name: Upload to S3
        run: |
          cd frontend
          aws s3 sync build/ s3://weekly-react-app --delete

      # 6. CloudFront 캐시 무효화 (최신 변경 사항 즉시 반영)
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/index.html" "/*"
